/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
 `default_nettype none

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule

module DIG_RAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
endmodule


module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Demux4
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel,
    input in
);
    assign out_0 = (sel == 4'h0)? in : Default;
    assign out_1 = (sel == 4'h1)? in : Default;
    assign out_2 = (sel == 4'h2)? in : Default;
    assign out_3 = (sel == 4'h3)? in : Default;
    assign out_4 = (sel == 4'h4)? in : Default;
    assign out_5 = (sel == 4'h5)? in : Default;
    assign out_6 = (sel == 4'h6)? in : Default;
    assign out_7 = (sel == 4'h7)? in : Default;
    assign out_8 = (sel == 4'h8)? in : Default;
    assign out_9 = (sel == 4'h9)? in : Default;
    assign out_10 = (sel == 4'ha)? in : Default;
    assign out_11 = (sel == 4'hb)? in : Default;
    assign out_12 = (sel == 4'hc)? in : Default;
    assign out_13 = (sel == 4'hd)? in : Default;
    assign out_14 = (sel == 4'he)? in : Default;
    assign out_15 = (sel == 4'hf)? in : Default;
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module RegisterBlock (
  input [15:0] DataIn,
  input WE,
  input clk,
  input [3:0] src,
  input [3:0] Dest,
  output [15:0] RDest,
  output [15:0] Rsrc
);
  wire s0;
  wire [15:0] s1;
  wire s2;
  wire [15:0] s3;
  wire s4;
  wire [15:0] s5;
  wire s6;
  wire [15:0] s7;
  wire s8;
  wire [15:0] s9;
  wire s10;
  wire [15:0] s11;
  wire s12;
  wire [15:0] s13;
  wire s14;
  wire [15:0] s15;
  wire s16;
  wire [15:0] s17;
  wire s18;
  wire [15:0] s19;
  wire s20;
  wire [15:0] s21;
  wire s22;
  wire [15:0] s23;
  wire s24;
  wire [15:0] s25;
  wire s26;
  wire [15:0] s27;
  wire s28;
  wire [15:0] s29;
  wire s30;
  wire [15:0] s31;
  Demux4 #(
    .Default(0)
  )
  Demux4_i0 (
    .sel( Dest ),
    .in( WE ),
    .out_0( s0 ),
    .out_1( s2 ),
    .out_2( s4 ),
    .out_3( s6 ),
    .out_4( s8 ),
    .out_5( s10 ),
    .out_6( s12 ),
    .out_7( s14 ),
    .out_8( s16 ),
    .out_9( s18 ),
    .out_10( s20 ),
    .out_11( s22 ),
    .out_12( s24 ),
    .out_13( s26 ),
    .out_14( s28 ),
    .out_15( s30 )
  );
  // R0
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i1 (
    .D( DataIn ),
    .C( clk ),
    .en( s0 ),
    .Q( s1 )
  );
  // R1
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i2 (
    .D( DataIn ),
    .C( clk ),
    .en( s2 ),
    .Q( s3 )
  );
  // R2
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i3 (
    .D( DataIn ),
    .C( clk ),
    .en( s4 ),
    .Q( s5 )
  );
  // R3
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i4 (
    .D( DataIn ),
    .C( clk ),
    .en( s6 ),
    .Q( s7 )
  );
  // R4
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( DataIn ),
    .C( clk ),
    .en( s8 ),
    .Q( s9 )
  );
  // R5
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i6 (
    .D( DataIn ),
    .C( clk ),
    .en( s10 ),
    .Q( s11 )
  );
  // R6
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i7 (
    .D( DataIn ),
    .C( clk ),
    .en( s12 ),
    .Q( s13 )
  );
  // R7
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i8 (
    .D( DataIn ),
    .C( clk ),
    .en( s14 ),
    .Q( s15 )
  );
  // R8
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i9 (
    .D( DataIn ),
    .C( clk ),
    .en( s16 ),
    .Q( s17 )
  );
  // R9
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i10 (
    .D( DataIn ),
    .C( clk ),
    .en( s18 ),
    .Q( s19 )
  );
  // R10
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i11 (
    .D( DataIn ),
    .C( clk ),
    .en( s20 ),
    .Q( s21 )
  );
  // R11
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i12 (
    .D( DataIn ),
    .C( clk ),
    .en( s22 ),
    .Q( s23 )
  );
  // R12
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i13 (
    .D( DataIn ),
    .C( clk ),
    .en( s24 ),
    .Q( s25 )
  );
  // BP
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i14 (
    .D( DataIn ),
    .C( clk ),
    .en( s26 ),
    .Q( s27 )
  );
  // SP
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i15 (
    .D( DataIn ),
    .C( clk ),
    .en( s28 ),
    .Q( s29 )
  );
  // RA
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i16 (
    .D( DataIn ),
    .C( clk ),
    .en( s30 ),
    .Q( s31 )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i17 (
    .sel( Dest ),
    .in_0( s1 ),
    .in_1( s3 ),
    .in_2( s5 ),
    .in_3( s7 ),
    .in_4( s9 ),
    .in_5( s11 ),
    .in_6( s13 ),
    .in_7( s15 ),
    .in_8( s17 ),
    .in_9( s19 ),
    .in_10( s21 ),
    .in_11( s23 ),
    .in_12( s25 ),
    .in_13( s27 ),
    .in_14( s29 ),
    .in_15( s31 ),
    .out( RDest )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i18 (
    .sel( src ),
    .in_0( s1 ),
    .in_1( s3 ),
    .in_2( s5 ),
    .in_3( s7 ),
    .in_4( s9 ),
    .in_5( s11 ),
    .in_6( s13 ),
    .in_7( s15 ),
    .in_8( s17 ),
    .in_9( s19 ),
    .in_10( s21 ),
    .in_11( s23 ),
    .in_12( s25 ),
    .in_13( s27 ),
    .in_14( s29 ),
    .in_15( s31 ),
    .out( Rsrc )
  );
endmodule

module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


// Register for storing large constants.
// There is a 1-bit command describing this register. 
// In this way, 15 bits can be stored (the 16th bit 
// activates the writing of this register and therefore 
// is always one). The 16th bit will be set according 
// to the 'immediate extend mode' (iem).
module ImReg (
  input en, // enables storage
  input [1:0] iem, // immediate extend mode (0: sign extend; 1: extend with 0, 2:extend with S0, 3:extend with D0)
  input C,
  input [15:0] inst, // the current instruction
  output [15:0] imm // The constant of register contents and bit 8.

);
  wire [14:0] s0;
  wire [14:0] s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s2 = inst[0];
  assign s3 = inst[4];
  assign s0 = inst[14:0];
  // imm
  DIG_Register_BUS #(
    .Bits(15)
  )
  DIG_Register_BUS_i0 (
    .D( s0 ),
    .C( C ),
    .en( en ),
    .Q( s1 )
  );
  assign s5 = s1[14];
  Mux_4x1 Mux_4x1_i1 (
    .sel( iem ),
    .in_0( s5 ),
    .in_1( 1'b0 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .out( s4 )
  );
  assign imm[14:0] = s1;
  assign imm[15] = s4;
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_JK_FF
#(
    parameter Default = 1'b0
)
(
   input J,
   input C,
   input K,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        if (~J & K)
            state <= 1'b0;
         else if (J & ~K)
            state <= 1'b1;
         else if (J & K)
            state <= ~state;
    end

    initial begin
        state = Default;
    end
endmodule


module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule

module DIG_ROM_4096X16_ptog (
    input [11:0] A,
    input sel,
    output reg [15:0] D
);
    reg [15:0] my_rom [0:22];

    always @ (*) begin
        if (~sel)
            D = 16'hz;
        else if (A > 12'h16)
            D = 16'h0;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 16'h3d02;
        my_rom[1] = 16'h0;
        my_rom[2] = 16'h4400;
        my_rom[3] = 16'h3f50;
        my_rom[4] = 16'h91ad;
        my_rom[5] = 16'h9c0;
        my_rom[6] = 16'h3f8c;
        my_rom[7] = 16'h4700;
        my_rom[8] = 16'h3f50;
        my_rom[9] = 16'h4700;
        my_rom[10] = 16'h3f50;
        my_rom[11] = 16'h4700;
        my_rom[12] = 16'h3f50;
        my_rom[13] = 16'h91ad;
        my_rom[14] = 16'h9c0;
        my_rom[15] = 16'h3f8c;
        my_rom[16] = 16'h4700;
        my_rom[17] = 16'h3f50;
        my_rom[18] = 16'h0;
        my_rom[19] = 16'h0;
        my_rom[20] = 16'h4700;
        my_rom[21] = 16'h3f50;
        my_rom[22] = 16'h3dec;
    end
endmodule


module singExtend (
  input [15:0] inst, // instruction word
  output [15:0] \4S , // The four bits taken from Rs.
  output [15:0] \8SD , // The eight bits taken from Rs,Rd with sign extension.
  output [15:0] \4D  // The four bits taken from Rd.

);
  wire s0;
  assign \4D [3:0] = inst[7:4];
  assign \4D [15:4] = 12'b0;
  assign \4S [3:0] = inst[3:0];
  assign \4S [15:4] = 12'b0;
  assign s0 = inst[7];
  assign \8SD [6:0] = inst[6:0];
  assign \8SD [7] = s0;
  assign \8SD [8] = s0;
  assign \8SD [9] = s0;
  assign \8SD [10] = s0;
  assign \8SD [11] = s0;
  assign \8SD [12] = s0;
  assign \8SD [13] = s0;
  assign \8SD [14] = s0;
  assign \8SD [15] = s0;
endmodule

module controllogic (
  input A,
  input B,
  input C,
  input D,
  input E,
  input F,
  input G,
  output muxb0,
  output muxb1,
  output muxb2,
  output src2D,
  output aluop0,
  output aluop1,
  output aluop2,
  output aluop3,
  output aluop4,
  output WE,
  output sf,
  output alu2D,
  output iem0,
  output iem1,
  output br0,
  output br1,
  output br2,
  output muxA,
  output ld,
  output st,
  output abs,
  output ioW,
  output ioR,
  output stPC,
  output Reti,
  output rand
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  assign s5 = ~ A;
  assign s0 = ~ B;
  assign s1 = ~ C;
  assign s2 = ~ D;
  assign s3 = ~ E;
  assign s6 = ~ F;
  assign s4 = ~ G;
  assign muxb0 = ((A & s0 & s1 & s2 & s3 & F & s4) | (A & s0 & s1 & s2 & E & F & G) | (s5 & s1 & D & E & F & s4) | (s5 & B & C & s3 & s6 & s4) | (s5 & s0 & s1 & D & F & s4) | (s5 & s0 & s1 & D & E & s4) | (s5 & s0 & C & s2 & s3 & s4) | (s5 & B & s1 & s2 & s3 & G) | (s5 & C & D & s6 & G) | (s5 & C & s2 & E & G) | (s5 & B & C & E & G) | (s5 & B & C & s2 & E));
  assign muxb1 = ((A & s0 & s1 & s2 & E & F & s4) | (s5 & C & s2 & s3 & s6 & G) | (s5 & B & s1 & s2 & s3 & s4) | (A & s0 & s1 & s2 & s3 & G) | (A & s0 & s1 & s2 & s3 & s6) | (s5 & s1 & D & F & G) | (s5 & C & D & s6 & s4) | (s5 & B & C & s6 & G) | (s5 & B & C & F & s4) | (s5 & C & s2 & E & s4) | (s5 & s0 & s1 & D & G) | (s5 & B & D & E) | (s5 & B & C & E));
  assign muxb2 = ((s5 & B & C & D & E & F & G) | (s5 & C & s2 & s3 & s6 & s4) | (s5 & B & s2 & s3 & F & G) | (s5 & B & s1 & s3 & F & G) | (s5 & s0 & s1 & D & F & s4) | (s5 & s0 & C & D & s6 & G) | (A & s0 & s1 & s2 & F & G) | (s5 & s0 & C & s2 & s3 & s4) | (s5 & s0 & C & s2 & E & G) | (s5 & B & s1 & s2 & s3 & G) | (A & s0 & s1 & s2 & s3 & s4) | (s5 & s1 & D & E & s4));
  assign src2D = ((s5 & s0 & s1 & s2 & s3 & s6 & G) | (s5 & B & s1 & D & s3 & F & G) | (s5 & B & s1 & D & E & s6 & G) | (s5 & B & C & s2 & s3 & s6 & G) | (A & s0 & s1 & s2 & s3 & s6 & s4) | (s5 & B & D & E & F & s4) | (s5 & B & C & D & E & F));
  assign aluop0 = ((s5 & s0 & s1 & D & E & F & s4) | (s5 & s0 & C & s2 & s3 & s6 & G) | (s5 & s0 & C & s2 & s3 & F & s4) | (s5 & s0 & C & D & E & F & G) | (s5 & s1 & s2 & s3 & F & G) | (s5 & s0 & s1 & E & s6 & G) | (s5 & B & s1 & s2 & F));
  assign aluop1 = ((s5 & s0 & C & D & s3 & F & G) | (A & s0 & s1 & s2 & E & s6 & G) | (A & s0 & s1 & s2 & E & F & s4) | (s5 & B & s1 & D & s3 & s4) | (s5 & s0 & C & D & E & s6) | (s5 & B & s1 & D & s3 & s6) | (s5 & B & s1 & s2 & E));
  assign aluop2 = ((s5 & B & s1 & D & s3 & F & s4) | (A & s0 & s1 & s2 & E & s6 & G) | (A & s0 & s1 & s2 & E & F & s4) | (s5 & s0 & s2 & E & F & G) | (s5 & s0 & D & s3 & s6 & s4) | (s5 & s0 & C & s3 & F & G) | (s5 & s0 & C & s2 & E & F) | (s5 & s0 & C & D & s6) | (s5 & s0 & C & D & s3));
  assign aluop3 = ((s5 & s0 & D & E & F & G) | (s5 & s0 & C & D & F & s4) | (s5 & s0 & s2 & E & s6) | (s5 & B & s1 & s3 & s6) | (s5 & s0 & C & s2 & s3) | (s5 & B & s1 & s2 & s3) | (s0 & s1 & s2 & E & s6 & G) | (s0 & s1 & s2 & E & F & s4));
  assign aluop4 = ((s5 & B & C & s2 & s3 & s6 & G) | (s5 & B & C & s2 & s3 & F & s4) | (A & s0 & s1 & s2 & s3 & s6 & s4) | (s5 & s1 & D & E & s6 & s4) | (s5 & s0 & s1 & E & F & s4) | (s5 & s0 & s1 & s2 & F & s4) | (s5 & s0 & C & D & s3 & G) | (s5 & B & s1 & s2 & E & G) | (s5 & B & s1 & D & s3 & G) | (s5 & s0 & s3 & F & G) | (s5 & s0 & D & s6 & s4) | (s5 & s0 & D & E & s6) | (s5 & s0 & C & E & s6) | (s0 & s1 & s2 & s3 & F & G));
  assign WE = ((s5 & D & s3 & F & s4) | (s5 & s1 & E & s6 & s4) | (s5 & s1 & E & F & G) | (s5 & C & s2 & s3 & s4) | (s5 & s1 & D & s3 & s6) | (s5 & C & s2 & s3 & F) | (s5 & s0 & D & s6) | (s5 & s1 & s2 & E) | (s5 & s0 & D & s3) | (s5 & s0 & s1 & D) | (s5 & s0 & C & s2) | (s0 & s1 & s2 & G) | (s0 & s1 & s2 & F));
  assign sf = ((s5 & s1 & D & s3 & s6 & s4) | (s5 & s0 & s2 & F & s4) | (s5 & s0 & D & F & G) | (s5 & s0 & s1 & F & G) | (s5 & s0 & C & s6) | (s5 & B & s1 & s2) | (s5 & s0 & E) | (s0 & s1 & s2 & E & s6 & G) | (s0 & s1 & s2 & E & F & s4));
  assign alu2D = ((s5 & C & s2 & s3 & F & G) | (s5 & s1 & D & s3 & s4) | (s5 & s1 & D & s3 & s6) | (s5 & s0 & E & s6) | (s5 & s0 & s2 & F) | (s5 & s0 & s1 & F) | (s5 & s1 & s2 & E) | (s5 & s0 & C & s3) | (s0 & s1 & s2 & E & s6 & G) | (s0 & s1 & s2 & E & F & s4));
  assign iem0 = ((s5 & s0 & C & s2 & s3 & s6 & G) | (A & s0 & s1 & s2 & s3 & s6 & G) | (A & s0 & s1 & s2 & E & F & s4) | (s5 & C & D & E & s6 & s4) | (s5 & s0 & C & D & s6 & s4) | (s5 & B & C & D & F & s4) | (s5 & s0 & C & s2 & E & s4) | (s5 & B & s1 & s2 & s3 & s4) | (s5 & s1 & D & E & G) | (s5 & s0 & s1 & D & G));
  assign iem1 = ((s5 & B & s1 & D & E & s6 & G) | (s5 & B & C & D & E & F & s4));
  assign br0 = ((s5 & B & C & s2 & E & F & G) | (s5 & B & C & D & s6 & G) | (s5 & B & C & D & s3 & s6));
  assign br1 = ((s5 & B & C & s2 & E & s6 & G) | (s5 & B & C & s2 & E & F & s4) | (s5 & B & C & D & s3 & s6));
  assign br2 = ((s5 & B & C & D & s3 & s6 & G) | (s5 & B & C & s2 & E & s4) | (s5 & B & C & s2 & E & F));
  assign muxA = ((s5 & B & s1 & D & E & s6 & s4) | (s5 & B & C & s2 & s3 & F & s4) | (A & s0 & s1 & s2 & s3 & G) | (A & s0 & s1 & s2 & s3 & F));
  assign ld = ((s5 & B & s1 & D & E & s6 & s4) | (s5 & B & s1 & D & E & F & G) | (s5 & B & C & s2 & s3 & s4));
  assign st = ((s5 & B & s1 & D & s3 & F & G) | (s5 & B & s1 & D & E & s6 & G) | (s5 & B & s1 & D & E & F & s4) | (s5 & B & C & s2 & s3 & s6 & G));
  assign abs = ((s5 & B & C & D & E & s6 & s4) | (A & s0 & s1 & s2 & E & s6 & s4) | (s5 & B & C & D & s3 & F));
  assign ioW = ((A & s0 & s1 & s2 & s3 & s6 & s4) | (s5 & B & C & D & E & F));
  assign ioR = ((A & s0 & s1 & s2 & s3 & G) | (A & s0 & s1 & s2 & s3 & F));
  assign stPC = (s5 & B & C & D & s3 & F & s4);
  assign Reti = (A & s0 & s1 & s2 & E & s6 & s4);
  assign rand = (A & s0 & s1 & s2 & E & F & G);
endmodule

// Arithmetic shift right. An unsigned division by two. 
// The lower bit is output as the carry bit, while the 
// uppermost bit remains unchanged in order to 
// obtain the sign.
module ASR (
  input [15:0] Di, // data input
  output C, // carry output
  output [15:0] Do // data output

);
  wire s0;
  assign C = Di[0];
  assign s0 = Di[15];
  assign Do[13:0] = Di[14:1];
  assign Do[14] = s0;
  assign Do[15] = s0;
endmodule

// Swaps the high-byte and the low-byte.
module SWAP (
  input [15:0] Di, // data input
  output [15:0] Do // data output

);
  assign Do[7:0] = Di[15:8];
  assign Do[15:8] = Di[7:0];
endmodule

// Swaps the 4-bit nibble in the high- and the low-byte.
module SWAPN (
  input [15:0] Di, // Data input
  output [15:0] Do // Data output

);
  assign Do[3:0] = Di[7:4];
  assign Do[7:4] = Di[3:0];
  assign Do[11:8] = Di[15:12];
  assign Do[15:12] = Di[11:8];
endmodule

module DIG_Neg #(
    parameter Bits = 1
)
(
      input signed [(Bits-1):0] in,
      output signed [(Bits-1):0] out
);
    assign out = -in;
endmodule


module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


// Moves the data word to the left to higher bits, so it multiplies 
// by two. The current carry bit is pushed in at the bottom, and 
// the most significant bit is output as a carry bit.
module LSL (
  input [15:0] Di, // data input
  input Ci, // carry input
  output [15:0] Do, // data output
  output Co // carry output

);
  assign Do[0] = Ci;
  assign Do[15:1] = Di[14:0];
  assign Co = Di[15];
endmodule

// Shift right. So a division by two.
// The carry bit is inserted at the top. And the least 
// significant bit is output as a new carry bit.
module LSR (
  input [15:0] Di, // data input
  input Ci, // carry input
  output [15:0] Do, // data output
  output Co // carry output

);
  assign Do[14:0] = Di[15:1];
  assign Do[15] = Ci;
  assign Co = Di[0];
endmodule

module DIG_Mul_unsigned #(
    parameter Bits = 1
)
(
    
      input [(Bits-1):0] a,
      input [(Bits-1):0] b,
      output [(Bits*2-1):0] mul
    
);
    assign mul = a * b;
endmodule


module Mux_16x1
(
    input [3:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    input in_8,
    input in_9,
    input in_10,
    input in_11,
    input in_12,
    input in_13,
    input in_14,
    input in_15,
    output reg out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module CompSigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = $signed(a) > $signed(b);
    assign \= = $signed(a) == $signed(b);
    assign \< = $signed(a) < $signed(b);
endmodule


module tt_um_smallScpu (
  input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
  wire muxA;
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [2:0] muxB;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [3:0] s9;
  wire [3:0] s10;
  wire [7:0] OPcode;
  wire [7:0] s11;
  wire st;
  wire s12;
  wire ld;
  wire [15:0] s13;
  wire [2:0] WDmux;
  wire [15:0] s14;
  wire [15:0] Din;
  wire [15:0] s15;
  wire [15:0] RandomNUM;
  wire [15:0] s16;
  wire [1:0] s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire [2:0] br;
  wire s23;
  wire sf;
  wire s24;
  wire s25;
  wire intr;
  wire interEn;
  wire [15:0] FlagOut;
  wire InterLock;
  wire imm;
  wire s26;
  wire s27;
  wire s28;
  wire Reti;
  wire s29;
  wire s30;
  wire inter;
  wire WE;
  wire [1:0] iem;
  wire [11:0] s31;
  wire s32;
  wire [11:0] pcOut;
  wire [11:0] s33;
  wire [11:0] s34;
  wire [11:0] s35;
  wire [11:0] s36;
  wire abs;
  wire [11:0] s37;
  wire [11:0] s38;
  wire s39;
  wire [11:0] s40;
  wire s41;
  wire ioW;
  wire s42;
  wire [3:0] s43;
  wire [3:0] outputToOutside;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire [7:0] s52;
  wire [7:0] s53;
  wire s54;
  wire [7:0] s55;
  wire s56;
  wire s57;
  wire [3:0] sel;
  wire [15:0] s58;
  wire [15:0] s59;
  wire [15:0] s60;
  wire [15:0] s61;
  wire [15:0] s62;
  wire [15:0] s63;
  wire [15:0] s64;
  wire [15:0] s65;
  wire [15:0] s66;
  wire [15:0] s67;
  wire [15:0] s68;
  wire [15:0] s69;
  wire [15:0] s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire [4:0] aluOp;
  wire [31:0] s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire [15:0] s83;
  wire [15:0] s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire s100;
  wire s101;
  wire s102;
  wire s103;
  wire s104;
  wire s105;
  wire s106;
  wire s107;
  wire s108;
  wire s109;
  wire s110;
  wire s111;
  wire s112;
  wire s113;
  wire s114;
  wire s115;
  wire s116;
  wire s117;
  wire s118;
  wire s119;
  wire s120;
  wire stPC;
  wire RandomNUMSel;
  wire ioR;
  wire [6:0] s121;
  wire [6:0] s122;
  wire s123;
  wire s124;
  wire s125;
  wire s126;
  wire s127;
  wire s128;
  wire s129;
  wire s130;
  wire s131;
  wire s132;
  wire src2D;
  wire s133;
  wire s134;
  wire s135;
  wire s136;
  wire s137;
  wire alu2D;
  wire s138;
  wire s139;
  wire s140;
  wire s141;
  wire s142;
  wire s143;
  wire s144;
  wire [3:0] s145;
  wire [3:0] outputToOutsideEnable;
  wire [7:0] s146;
  wire s147;
  wire s148;
  wire [7:0] s149;
  wire [7:0] s150;
  wire s151;
  wire [7:0] s152;
  wire [1:0] s153;
  wire s154;
  wire s155;
  wire [15:0] s156;
  wire [7:0] s157;
  wire [7:0] s158;
  assign s147 = ~ clk;
  DIG_Counter_Nbit #(
    .Bits(2)
  )
  DIG_Counter_Nbit_i0 (
    .en( 1'b1 ),
    .C( clk ),
    .clr( rst_n ),
    .out( s153 )
  );
  assign s44 = uio_in[0];
  assign s45 = uio_in[1];
  assign s46 = uio_in[2];
  assign s47 = uio_in[3];
  assign s48 = uio_in[4];
  assign s49 = uio_in[5];
  assign s50 = uio_in[6];
  assign s51 = uio_in[7];
  assign Din[0] = s44;
  assign Din[1] = s45;
  assign Din[2] = s46;
  assign Din[3] = s47;
  assign Din[4] = s48;
  assign Din[5] = s49;
  assign Din[6] = s50;
  assign Din[7] = s51;
  assign Din[8] = 1'b0;
  assign Din[9] = 1'b0;
  assign Din[10] = 1'b0;
  assign Din[11] = 1'b0;
  assign Din[12] = 1'b0;
  assign Din[13] = 1'b0;
  assign Din[14] = 1'b0;
  assign Din[15] = 1'b0;
  assign s52[0] = s44;
  assign s52[1] = s45;
  assign s52[2] = s46;
  assign s52[3] = s47;
  assign s52[4] = s48;
  assign s52[5] = s49;
  assign s52[6] = s50;
  assign s52[7] = s51;
  assign s154 = s153[0];
  assign s155 = s153[1];
  assign s148 = (s154 & ~ s155);
  assign s151 = (~ s154 & s155);
  assign s12 = (s154 & s155);
  assign s28 = ~ s12;
  assign s30 = ~ s12;
  assign s32 = ~ s12;
  assign s39 = ~ s12;
  assign s54 = ~ s12;
  // mem
  DIG_RAMDualPort #(
    .Bits(16),
    .AddrBits(8)
  )
  DIG_RAMDualPort_i1 (
    .A( s11 ),
    .Din( s1 ),
    .str( st ),
    .C( s12 ),
    .ld( ld ),
    .D( s13 )
  );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i2 (
    .sel( WDmux ),
    .in_0( s14 ),
    .in_1( s13 ),
    .in_2( Din ),
    .in_3( s15 ),
    .in_4( 16'b0 ),
    .in_5( RandomNUM ),
    .in_6( 16'b0 ),
    .in_7( 16'b0 ),
    .out( s16 )
  );
  // Carry
  DIG_Register DIG_Register_i3 (
    .D( s23 ),
    .C( s12 ),
    .en( sf ),
    .Q( s18 )
  );
  // Zero
  DIG_Register DIG_Register_i4 (
    .D( s24 ),
    .C( s12 ),
    .en( sf ),
    .Q( s19 )
  );
  // Neg
  DIG_Register DIG_Register_i5 (
    .D( s25 ),
    .C( s12 ),
    .en( sf ),
    .Q( s20 )
  );
  // inter1
  DIG_Register DIG_Register_i6 (
    .D( intr ),
    .C( s12 ),
    .en( sf ),
    .Q( interEn )
  );
  // *
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s27 ),
    .C( s28 ),
    .Q( InterLock )
  );
  // *
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( s29 ),
    .C( s30 ),
    .Q( s26 )
  );
  RegisterBlock RegisterBlock_i9 (
    .DataIn( s16 ),
    .WE( WE ),
    .clk( s12 ),
    .src( s9 ),
    .Dest( s10 ),
    .RDest( s0 ),
    .Rsrc( s1 )
  );
  ImReg ImReg_i10 (
    .en( imm ),
    .iem( iem ),
    .C( s12 ),
    .inst( s8 ),
    .imm( s3 )
  );
  // PC
  DIG_Register_BUS #(
    .Bits(12)
  )
  DIG_Register_BUS_i11 (
    .D( s31 ),
    .C( s32 ),
    .en( 1'b1 ),
    .Q( pcOut )
  );
  DIG_Register_BUS #(
    .Bits(12)
  )
  DIG_Register_BUS_i12 (
    .D( s37 ),
    .C( s39 ),
    .en( intr ),
    .Q( s40 )
  );
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i13 (
    .D( s43 ),
    .C( s12 ),
    .en( s42 ),
    .Q( outputToOutside )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i14 (
    .D( s53 ),
    .C( s54 ),
    .en( inter ),
    .Q( s55 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i15 (
    .sel( InterLock ),
    .in_0( s52 ),
    .in_1( s55 ),
    .out( s53 )
  );
  // seed
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i16 (
    .D( s1 ),
    .C( s12 ),
    .en( s82 ),
    .Q( s83 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i17 (
    .J( s86 ),
    .C( s12 ),
    .K( s86 ),
    .Q( s80 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i18 (
    .Set( s88 ),
    .D( s89 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s90 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i19 (
    .Set( s91 ),
    .D( s90 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s92 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i20 (
    .Set( s93 ),
    .D( s92 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s94 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i21 (
    .Set( s95 ),
    .D( s94 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s96 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i22 (
    .Set( s97 ),
    .D( s96 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s98 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i23 (
    .Set( s99 ),
    .D( s98 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s100 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i24 (
    .Set( s101 ),
    .D( s100 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s102 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i25 (
    .Set( s103 ),
    .D( s102 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s104 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i26 (
    .Set( s105 ),
    .D( s104 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s106 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i27 (
    .Set( s107 ),
    .D( s106 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s108 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i28 (
    .Set( s109 ),
    .D( s108 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s110 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i29 (
    .Set( s111 ),
    .D( s110 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s112 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i30 (
    .Set( s113 ),
    .D( s112 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s114 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i31 (
    .Set( s115 ),
    .D( s114 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s116 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i32 (
    .Set( s117 ),
    .D( s116 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s118 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i33 (
    .Set( s119 ),
    .D( s118 ),
    .C( s12 ),
    .Clr( s87 ),
    .Q( s120 )
  );
  assign s79 = (s12 & s82);
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i34 (
    .D( s145 ),
    .C( s12 ),
    .en( s144 ),
    .Q( outputToOutsideEnable )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i35 (
    .D( s146 ),
    .C( s147 ),
    .en( s148 ),
    .Q( s149 )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i36 (
    .D( s150 ),
    .C( s147 ),
    .en( s151 ),
    .Q( s152 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i37 (
    .sel( 1'b0 ),
    .in_0( ui_in ),
    .in_1( s157 ),
    .out( s150 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i38 (
    .sel( 1'b0 ),
    .in_0( ui_in ),
    .in_1( s158 ),
    .out( s146 )
  );
  assign FlagOut[0] = s18;
  assign FlagOut[1] = s19;
  assign FlagOut[2] = s20;
  assign FlagOut[3] = interEn;
  assign FlagOut[15:4] = 12'b0;
  // Add One
  DIG_Add #(
    .Bits(12)
  )
  DIG_Add_i39 (
    .a( pcOut ),
    .b( 12'b1 ),
    .c_i( 1'b0 ),
    .s( s33 )
  );
  CompUnsigned #(
    .Bits(8)
  )
  CompUnsigned_i40 (
    .a( s53 ),
    .b( s55 ),
    .\> ( s56 ),
    .\< ( s57 )
  );
  assign s89 = (s100 ^ (s110 ^ (s114 ^ s118)));
  assign RandomNUM[0] = s90;
  assign RandomNUM[1] = s92;
  assign RandomNUM[2] = s94;
  assign RandomNUM[3] = s96;
  assign RandomNUM[4] = s98;
  assign RandomNUM[5] = s100;
  assign RandomNUM[6] = s102;
  assign RandomNUM[7] = s104;
  assign RandomNUM[8] = s106;
  assign RandomNUM[9] = s108;
  assign RandomNUM[10] = s110;
  assign RandomNUM[11] = s112;
  assign RandomNUM[12] = s114;
  assign RandomNUM[13] = s116;
  assign RandomNUM[14] = s118;
  assign RandomNUM[15] = s120;
  assign uio_out[3:0] = pcOut[11:8];
  assign uio_out[7:4] = outputToOutside;
  assign uio_oe[3:0] = 4'b0;
  assign uio_oe[7:4] = outputToOutsideEnable;
  assign s8[7:0] = s152;
  assign s8[15:8] = s149;
  // ptog
  DIG_ROM_4096X16_ptog DIG_ROM_4096X16_ptog_i41 (
    .A( pcOut ),
    .sel( 1'b1 ),
    .D( s156 )
  );
  assign s43 = s1[3:0];
  assign s145 = s1[3:0];
  assign uo_out = pcOut[7:0];
  singExtend singExtend_i42 (
    .inst( s8 ),
    .\4S ( s4 ),
    .\8SD ( s5 ),
    .\4D ( s6 )
  );
  assign inter = (s56 | s57);
  assign s15[11:0] = s33;
  assign s15[15:12] = 4'b0;
  assign s9 = s8[3:0];
  assign s10 = s8[7:4];
  assign OPcode = s8[15:8];
  assign s157 = s156[7:0];
  assign s158 = s156[15:8];
  assign s121 = OPcode[6:0];
  assign imm = OPcode[7];
  assign intr = (~ InterLock & ~ imm & s26 & ~ interEn);
  Mux_2x1_NBits #(
    .Bits(7)
  )
  Mux_2x1_NBits_i43 (
    .sel( imm ),
    .in_0( s121 ),
    .in_1( 7'b0 ),
    .out( s122 )
  );
  assign s129 = s122[0];
  assign s128 = s122[1];
  assign s127 = s122[2];
  assign s126 = s122[3];
  assign s125 = s122[4];
  assign s124 = s122[5];
  assign s123 = s122[6];
  controllogic controllogic_i44 (
    .A( s123 ),
    .B( s124 ),
    .C( s125 ),
    .D( s126 ),
    .E( s127 ),
    .F( s128 ),
    .G( s129 ),
    .muxb0( s130 ),
    .muxb1( s131 ),
    .muxb2( s132 ),
    .src2D( src2D ),
    .aluop0( s133 ),
    .aluop1( s134 ),
    .aluop2( s135 ),
    .aluop3( s136 ),
    .aluop4( s137 ),
    .WE( WE ),
    .sf( sf ),
    .alu2D( alu2D ),
    .iem0( s138 ),
    .iem1( s139 ),
    .br0( s140 ),
    .br1( s141 ),
    .br2( s142 ),
    .muxA( muxA ),
    .ld( ld ),
    .st( st ),
    .abs( abs ),
    .ioW( ioW ),
    .ioR( ioR ),
    .stPC( stPC ),
    .Reti( Reti ),
    .rand( RandomNUMSel )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i45 (
    .sel( muxA ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  assign s27 = ((InterLock & ~ Reti) | intr);
  assign s29 = ((s26 & ~ Reti) | inter);
  assign WDmux[0] = (stPC | ld | RandomNUMSel);
  assign WDmux[1] = (ioR | stPC);
  assign WDmux[2] = RandomNUMSel;
  assign muxB[0] = s132;
  assign muxB[1] = s131;
  assign muxB[2] = s130;
  assign aluOp[0] = s137;
  assign aluOp[1] = s136;
  assign aluOp[2] = s135;
  assign aluOp[3] = s134;
  assign aluOp[4] = s133;
  assign br[0] = s142;
  assign br[1] = s141;
  assign br[2] = s140;
  assign iem[0] = s139;
  assign iem[1] = s138;
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i46 (
    .sel( muxB ),
    .in_0( s1 ),
    .in_1( 16'b0 ),
    .in_2( s3 ),
    .in_3( 16'b0 ),
    .in_4( 16'b0 ),
    .in_5( s4 ),
    .in_6( s5 ),
    .in_7( s6 ),
    .out( s7 )
  );
  assign s71 = (aluOp[4] & s18);
  ASR ASR_i47 (
    .Di( s2 ),
    .C( s76 ),
    .Do( s67 )
  );
  SWAP SWAP_i48 (
    .Di( s2 ),
    .Do( s68 )
  );
  SWAPN SWAPN_i49 (
    .Di( s2 ),
    .Do( s69 )
  );
  assign s63 = ~ s2;
  DIG_Neg #(
    .Bits(16)
  )
  DIG_Neg_i50 (
    .in( s2 ),
    .out( s64 )
  );
  assign s17 = br[1:0];
  assign sel = aluOp[3:0];
  Mux_4x1 Mux_4x1_i51 (
    .sel( s17 ),
    .in_0( 1'b0 ),
    .in_1( s18 ),
    .in_2( s19 ),
    .in_3( s20 ),
    .out( s21 )
  );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i52 (
    .a( s2 ),
    .b( s7 ),
    .c_i( s71 ),
    .s( s58 ),
    .c_o( s72 )
  );
  DIG_Sub #(
    .Bits(16)
  )
  DIG_Sub_i53 (
    .a( s2 ),
    .b( s7 ),
    .c_i( s71 ),
    .s( s59 ),
    .c_o( s73 )
  );
  assign s60 = (s2 & s7);
  assign s61 = (s2 | s7);
  assign s62 = (s2 ^ s7);
  LSL LSL_i54 (
    .Di( s2 ),
    .Ci( s71 ),
    .Do( s65 ),
    .Co( s74 )
  );
  LSR LSR_i55 (
    .Di( s2 ),
    .Ci( s71 ),
    .Do( s66 ),
    .Co( s75 )
  );
  DIG_Mul_unsigned #(
    .Bits(16)
  )
  DIG_Mul_unsigned_i56 (
    .a( s2 ),
    .b( s7 ),
    .mul( s77 )
  );
  assign s22 = (s21 ^ br[2]);
  Mux_16x1 Mux_16x1_i57 (
    .sel( sel ),
    .in_0( 1'b0 ),
    .in_1( s72 ),
    .in_2( s73 ),
    .in_3( 1'b0 ),
    .in_4( 1'b0 ),
    .in_5( 1'b0 ),
    .in_6( 1'b0 ),
    .in_7( 1'b0 ),
    .in_8( s74 ),
    .in_9( s75 ),
    .in_10( s76 ),
    .in_11( 1'b0 ),
    .in_12( 1'b0 ),
    .in_13( 1'b0 ),
    .in_14( 1'b0 ),
    .in_15( 1'b0 ),
    .out( s23 )
  );
  assign s70 = s77[15:0];
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i58 (
    .sel( sel ),
    .in_0( s7 ),
    .in_1( s58 ),
    .in_2( s59 ),
    .in_3( s60 ),
    .in_4( s61 ),
    .in_5( s62 ),
    .in_6( s63 ),
    .in_7( s64 ),
    .in_8( s65 ),
    .in_9( s66 ),
    .in_10( s67 ),
    .in_11( s68 ),
    .in_12( s69 ),
    .in_13( s70 ),
    .in_14( 16'b0 ),
    .in_15( 16'b0 ),
    .out( s14 )
  );
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i59 (
    .a( s14 ),
    .b( 16'b101 ),
    .\= ( s41 )
  );
  CompSigned #(
    .Bits(16)
  )
  CompSigned_i60 (
    .a( s14 ),
    .b( 16'b0 ),
    .\= ( s24 )
  );
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i61 (
    .a( s14 ),
    .b( 16'b1000 ),
    .\= ( s85 )
  );
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i62 (
    .a( s14 ),
    .b( 16'b110 ),
    .\= ( s143 )
  );
  assign s11 = s14[7:0];
  assign s25 = s14[15];
  assign s34 = s14[11:0];
  // Add ALU
  DIG_Add #(
    .Bits(12)
  )
  DIG_Add_i63 (
    .a( s33 ),
    .b( s34 ),
    .c_i( 1'b0 ),
    .s( s35 )
  );
  assign s42 = (s41 & ioW);
  assign s82 = (s85 & ioW);
  assign s144 = (s143 & ioW);
  Mux_2x1_NBits #(
    .Bits(12)
  )
  Mux_2x1_NBits_i64 (
    .sel( s22 ),
    .in_0( s33 ),
    .in_1( s35 ),
    .out( s36 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i65 (
    .sel( s82 ),
    .in_0( 16'b0 ),
    .in_1( s83 ),
    .out( s84 )
  );
  Mux_2x1_NBits #(
    .Bits(12)
  )
  Mux_2x1_NBits_i66 (
    .sel( abs ),
    .in_0( s36 ),
    .in_1( s34 ),
    .out( s37 )
  );
  assign s88 = s84[0];
  assign s91 = s84[1];
  assign s93 = s84[2];
  assign s95 = s84[3];
  assign s97 = s84[4];
  assign s99 = s84[5];
  assign s101 = s84[6];
  assign s103 = s84[7];
  assign s105 = s84[8];
  assign s107 = s84[9];
  assign s109 = s84[10];
  assign s111 = s84[11];
  assign s113 = s84[12];
  assign s115 = s84[13];
  assign s117 = s84[14];
  assign s119 = s84[15];
  Mux_2x1_NBits #(
    .Bits(12)
  )
  Mux_2x1_NBits_i67 (
    .sel( intr ),
    .in_0( s37 ),
    .in_1( 12'b10 ),
    .out( s38 )
  );
  Mux_2x1_NBits #(
    .Bits(12)
  )
  Mux_2x1_NBits_i68 (
    .sel( Reti ),
    .in_0( s38 ),
    .in_1( s40 ),
    .out( s31 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i69 (
    .Set( 1'b0 ),
    .D( s78 ),
    .C( s79 ),
    .Clr( s80 ),
    .Q( s81 ),
    .\~Q ( s78 )
  );
  assign s86 = (s81 | s80);
  assign s87 = (s82 & ~ s86);
endmodule
