-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY IEEE;
  use ieee.std_logic_1164.all;

entity DIG_JK_FF_AS is
  generic (tempval : std_logic);
  port (
    Q    : out std_logic;
    notQ : out std_logic;
    Set  : in  std_logic;
    J    : in  std_logic;
    C    : in  std_logic;
    K    : in  std_logic;
    Clr  : in  std_logic);
end entity;

architecture Behavioral of DIG_JK_FF_AS is
  signal state : std_logic := tempval;
begin
  process (C, Clr, Set)
  begin
    if (Set = '1') then
      state <= '1';
    elsif (Clr = '1') then
      state <= '0';
    elsif rising_edge(C) then
      if (J = '0' and K = '1') then
        state <= '0';
      elsif (J = '1' and K = '0') then
        state <= '1';
      elsif (J = '1' and K = '1') then
        state <= not (state);
      end if;
    end if;
  end process;

  Q    <= state;
  notQ <= not (state);
end architecture;

