-- generated by digital. don't modify this file!
-- any changes will be lost if this file is regenerated.

LIBRARY IEEE;
  use ieee.std_logic_1164.all;

entity dig_jk_ff_as is
  generic (tempval : std_logic);
  port (
    q    : out std_logic;
    notq : out std_logic;
    set  : in  std_logic;
    j    : in  std_logic;
    c    : in  std_logic;
    k    : in  std_logic;
    clr  : in  std_logic);
end entity;

architecture behavioral of dig_jk_ff_as is
  signal state : std_logic := tempval;
begin
  process (c, clr, set)
  begin
    if (set = '1') then
      state <= '1';
    elsif (clr = '1') then
      state <= '0';
    elsif rising_edge(c) then
      if (j = '0' and k = '1') then
        state <= '0';
      elsif (j = '1' and k = '0') then
        state <= '1';
      elsif (j = '1' and k = '1') then
        state <= not (state);
      end if;
    end if;
  end process;

  q    <= state;
  notq <= not (state);
end architecture;

